name: Build and Deploy (Docker Hub)

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: shiranorg/my-express-app
  APP_NAME: employee
  RESOURCE_GROUP: azure-acr

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Login to Docker Hub
    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build Image
    - name: Build Docker Image
      run: |
        docker build -t $IMAGE_NAME:latest .

    # 4. Push Image
    - name: Push Docker Image
      run: |
        docker push $IMAGE_NAME:latest

    # 5. Login to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 6. Restart App Service
    - name: Restart App
      run: |
        az webapp restart \
          --name $APP_NAME \
          --resource-group $RESOURCE_GROUP